/*
 * QEDIT - Asset Transfers
 *
 * This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
 *
 * API version: 1.6.1
 * Contact: dev@qed-it.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sdk

type AnalyticsOutputDescription struct {
	// The commitment to both the Asset Type and amount of the Note
	Cv string `json:"cv,omitempty"`
	// The commitment to the entire Note
	Cm string `json:"cm,omitempty"`
	// The Proof that the commitments match
	Zkproof string `json:"zkproof,omitempty"`
	// The ephemeral public key used to encrypt the Note contents for the receiver
	Epk string `json:"epk,omitempty"`
	// The Note encryption for the receiver
	EncNote string `json:"enc_note,omitempty"`
	// The Note encryption for the sender
	EncSender string `json:"enc_sender,omitempty"`
}
